version: '3.8'

services:
  web:
    container_name: web
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:rw
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      poetry run python manage.py migrate &&
      poetry run python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"

  db:
    container_name: db
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: